### API 1 POST
POST http://localhost:3001/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

### API 2 POST
POST http://localhost:3001/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

### API 3 GET
GET http://localhost:3001/user/tweets/feed/?username=JoeBiden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk

### API 3 GET =>without sending Authorization in headers
GET http://localhost:3001/user/tweets/feed/

### API 3 GET =>without sending token in Authorization
GET http://localhost:3001/user/tweets/feed/
Authorization:Bearer

### API 3 GET =>without sending incorrect token in Authorization
GET http://localhost:3001/user/tweets/feed/
Authorization:Bearer pr-0VY1GVd5EpndR7ua3Ta1H7nrDOzZi

### API 4 GET
GET http://localhost:3001/user/following/?username=JoeBiden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk

### API 5 GET
GET http://localhost:3001/user/followers/?username=JoeBiden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk

### API 6 GET
GET http://localhost:3001/tweets/1/?username=JoeBiden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk

### API 7 GET
GET http://localhost:3001/tweets/2/likes/?username=JoeBiden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk

### API 8 GET
GET http://localhost:3001/tweets/1/replies/?name=Joe%20Biden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk

### API 9 GET
GET http://localhost:3001/user/tweets/?username=JoeBiden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk

### API 10 POST
POST http://localhost:3001/user/tweets/?user_id=2
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

### API 11 DELETE:
DELETE http://localhost:3001/tweets/2/?username=JoeBiden
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjkxOTkzNDUzfQ.Otz8rA6GKJBBJYmRyO1DXNA4W33egNsb5sIKkFU43xk
